Repository eda-se/eda, pull requests merged in 2024-06, with the labels that each got.

#19 Podstawowe statystyki 2d dla zmiennych numerycznych
  Pipfile
  Pipfile.lock
  app.py
  eda/components/statistics_1d.py
  eda/components/statistics_2d.py
  eda/destats.py
  requirements.txt
Labels: enhancement

#21 Filtrowanie, sortowanie, usuwanie oraz edycja wierszy, reset do konfiguracji początkowej
  eda/data_table/data_table.py
Labels: enhancement

#20 Wykrywanie i poprawa wartości brakujących i odstających
  app.py
  eda/data_correction/__init__.py
  eda/data_correction/data_correction.py
  eda/data_correction/missing_values.py
  eda/data_correction/outliers.py
Labels: enhancement

#23 Wykresy statystyk 1D
  eda/components/statistics_1d.py
Labels: enhancement

#28 Aktualizacja oprawy graficznej
  app.py
  assets/css/main.css
  assets/image/main-bg.png
  eda/components/__init__.py
  eda/components/statistics_1d.py
  eda/components/statistics_2d.py
  eda/data_correction/data_correction.py
  eda/data_table/data_table.py
  eda/file_input/file_input.py
Labels: enhancement

#29 Inicjalizacja środowiska wdrożeniowego
  Pipfile
  Pipfile.lock
  app.py
  requirements.txt
Labels: enhancement

#30 Poprawka wdrożenia
  app.py
Labels: bug

#32 Naprawa środowiska rozwojowego
  app.py
Labels: bug

#24 Wykresy dla statystyk 2D
  app.py
  eda/components/graph.py
  eda/components/graphs.py
  eda/components/statistics_1d.py
  eda/components/statistics_2d.py
  eda/data_table/column_type.py
Labels: enhancement

#31 Zapisywanie wyników do pliku CSV
  eda/components/__init__.py
  eda/data_correction/data_correction.py
  eda/data_table/data_table.py
  eda/file_input/csv_parser.py
  eda/file_input/file_input.py
Labels: enhancement

#34 Dodanie możliwości ustawienia separatorów
  app.py
  assets/css/main.css
  eda/data_table/data_table.py
  eda/file_input/csv_parser.py
  eda/file_input/file_input.py
Labels: enhancement

#35 Ulepszenie manipulacji typów
  app.py
  eda/data_table/column_type.py
  eda/data_table/data_table.py
  eda/file_input/csv_parser.py
  eda/file_input/file_input.py
Labels: enhancement

#36 Naprawienie rzutowania dla typów całkowitoliczbowych
  eda/data_table/column_type.py
Labels: bug

#38 Drobne zmiany w CSS
  assets/css/main.css
Labels: bug, enhancement

#39 Wybór wielu zmiennych dla statystyk jednowymiarowych
  eda/components/statistics_1d.py
Labels: enhancement

#41 Fix initial rendering of missing value table
  eda/data_correction/data_correction.py
Labels: bug

#42 Fix navigation, add big z-index
  assets/css/main.css
Labels: bug

#43 Display charts in grid view
  eda/components/statistics_1d.py
  eda/components/statistics_2d.py
Labels: enhancement
